[config]
skip_core_tasks = true

[tasks.build]
dependencies = ["build:wasm", "build:postbuild"]

[tasks."build:wasm"]
command = "cargo"
args = ["build", "--target", "wasm32-wasip1", "--release"]

[tasks."build:postbuild"]
command = "cargo"
args = ["run", "--bin", "postbuild"]

[tasks.default]
dependencies = ["fmt", "check", "build"]

[tasks.fmt]
dependencies = ["fmt:deno", "fmt:cargo"]

[tasks."fmt:deno"]
command = "deno"
args = ["src/plugin.ts"]

[tasks."fmt:cargo"]
command = "cargo"
args = ["fmt"]

[tasks.check]
dependencies = ["check:deno", "check:cargo"]

[tasks."check:deno"]
command = "deno"
args = ["check", "src/plugin.ts"]

[tasks."check:cargo"]
command = "cargo"
args = ["check"]
